name: Log Minecraft size

on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Minecraft
        id: cache-minecraft
        uses: actions/cache@v3
        with:
          path: minecraft
          key: minecraft-1.19.2-client

      - if: steps.cache-minecraft.outputs.cache-hit != 'true'
        uses: BenjaminMoran/download-minecraft-action@v1
        with:
          version: '1.19.2'
          files: client
          destination: minecraft

      - name: Log size
        run: wc -c minecraft/client.jar
